# Supervised pretraining config using 10% labeled nuScenes data.
#
# Requires the following pkls under data_root (default: data/nuscenes/):
# - nuscenes_infos_labeled_10.pkl   (generated by: python tools/create_data_bevdet.py semi --ratio 10 --percent 10)
# - nuscenes_infos_val.pkl          (generated by: python tools/create_data_bevdet.py prep, then optionally add_ann)

_base_ = ['./bevdet-r50.py']

# Keep this config self-contained (avoid relying on variables from base configs).
data_root = 'data/nuscenes/'

# Override annotation pkls to use the 10% labeled split for supervised pretraining.
data = dict(
    train=dict(ann_file=data_root + 'nuscenes_infos_labeled_10.pkl'),
    val=dict(ann_file=data_root + 'nuscenes_infos_val.pkl'),
    test=dict(ann_file=data_root + 'nuscenes_infos_val.pkl'),
)


